module.exports = {
  EN_ATTENTE_MANAGER: 'EN_ATTENTE_MANAGER',
  VALIDEE_MANAGER: 'VALIDEE_MANAGER',
  REFUSEE: 'REFUSEE',
  EN_ATTENTE_RELEX: 'EN_ATTENTE_RELEX',
  EN_ATTENTE_FINANCE: 'EN_ATTENTE_FINANCE',
  CLOTUREE: 'CLOTUREE',
  EFFECTUEE: 'EFFECTUEE'
};
